export const mockLostFoundPets: Pet[] = [
	{
		id: 1,
		name: 'Young dog',
		animal: 'dog',
		location: '41.300205, 2.104007',
		city: 'Barcelona',
		status: 'found',
		color: 'brown',
		description: 'Yellow and red collar',
		characteristics: [
			'cute',
			'friendly',
			'hypoallergenic',
			'shy',
			'happy in an apartment',
			'excellent companion for quiet activities',
		],
		size: 'm',
		gender: 'male',
		age: 'adult',
		breed: 'Labrador',
		address: 'Carrer de la Plaça, 1',
		lostDate: '30/06/2024',
		foundDate: '01/07/2024',
		petImages: [
			{ id: 1, src: '/img/dog-1.jpg' },
			{ id: 2, src: '/img/dog-2.jpg' },
			{ id: 3, src: '/img/dog-3.jpg' },
			{ id: 4, src: '/img/dog-4.jpg' },
			{ id: 5, src: '/img/dog-5.jpg' },
		],
	},
	{
		id: 2,
		name: 'Waldo',
		animal: 'cat',
		location: '41.300205, 2.104007',
		city: 'Barcelona',
		status: 'lost',
		color: 'brown',
		description: 'Yellow and red collar',
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Golden Retriever',
		address: 'Carrer de la Plaça, 1',
		lostDate: '30/06/2024',
		foundDate: '01/07/2024',
		petImages: [
			{ id: 1, src: '/img/dog-1.jpg' },
			{ id: 2, src: '/img/dog-2.jpg' },
			{ id: 3, src: '/img/dog-3.jpg' },
			{ id: 4, src: '/img/dog-4.jpg' },
			{ id: 5, src: '/img/dog-5.jpg' },
		],
	},
	{
		id: 3,
		name: 'Fluffy',
		animal: 'cat',
		location: '41.300205, 2.104007',
		city: 'Barcelona',
		status: 'lost',
		color: 'white',
		description: 'Yellow and red collar',
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'female',
		age: 'adult',
		breed: 'Persian',
		address: 'Carrer de la Plaça, 1',
		lostDate: '30/06/2024',
		petImages: [
			{ id: 1, src: '/img/cat-5.jpg' },
			{ id: 2, src: '/img/cat-2.jpg' },
			{ id: 3, src: '/img/cat-3.jpg' },
			{ id: 4, src: '/img/cat-4.jpg' },
			{ id: 5, src: '/img/cat-1.jpg' },
		],
	},
	{
		id: 4,
		name: 'Max',
		animal: 'dog',
		location: '41.300205, 2.104007',
		city: 'Barcelona',
		status: 'lost',
		color: 'black',
		description: 'Yellow and red collar',
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Labrador',
		address: 'Carrer de la Plaça, 1',
		lostDate: '30/06/2024',
		petImages: [
			{ id: 1, src: '/img/dog-3.jpg' },
			{ id: 2, src: '/img/dog-2.jpg' },
			{ id: 3, src: '/img/dog-1.jpg' },
			{ id: 4, src: '/img/dog-4.jpg' },
			{ id: 5, src: '/img/dog-5.jpg' },
		],
	},
];

export const mockPets: Pet[] = [
	{
		id: 1,
		name: 'Fluffy',
		animal: 'cat',
		location: '41.402384,2.151941',
		city: 'Barcelona',
		status: 'urgent',
		color: 'brown',
		description: `I'm a sweet and loving senior orange tabby looking for my forever home. At 10 years young, I still have plenty of love to give and snuggles to share! I'm the kind of kitty who enjoys the simple pleasures in life: a cozy spot by the window to watch the world go by, a gentle scratch behind the ears, and curling up on a warm lap for a long nap. I might be a bit older, but that just means I've perfected the art of being the best companion you could ever ask for. I'm calm, gentle, and would do wonderfully in a quiet home where I can spend my golden years surrounded by love.`,
		characteristics: [
			'cute',
			'friendly',
			'hypoallergenic',
			'shy',
			'happy in an apartment',
			'excellent companion',
		],
		size: 's',
		gender: 'female',
		age: 'adult',
		breed: 'Persian',
		petImages: [
			{ id: 1, src: '/img/cat-1.jpg' },
			{ id: 2, src: '/img/cat-2.jpg' },
			{ id: 3, src: '/img/cat-3.jpg' },
			{ id: 4, src: '/img/cat-4.jpg' },
			{ id: 5, src: '/img/cat-5.jpg' },
		],
	},
	{
		id: 2,
		name: 'Luna',
		animal: 'dog',
		location: '37.38,-5.97',
		city: 'Sevilla',
		color: 'gold',
		description: `I'm Luna, energetic and friendly Cocker Spaniel.`,
		characteristics: ['cute', 'friendly'],
		size: 'm',
		gender: 'female',
		age: 'adult',
		breed: 'Cocker Spaniel',
		petImages: [
			{ id: 1, src: '/img/dog-4.jpg' },
			{ id: 2, src: '/img/dog-2.jpg' },
			{ id: 3, src: '/img/dog-3.jpg' },
		],
	},
	{
		id: 3,
		name: 'Charlie',
		animal: 'rabbit',
		location: '41.380205,2.154007',
		city: 'Barcelona',
		color: 'white',
		description: `Hi, I’m Charlie! A gentle and affectionate rabbit looking for a calm, loving home where I can be your quiet companion. I love nibbling on fresh veggies and finding a cozy corner to relax in. I'm easy to care for and would be a great addition to any family.`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'senior',
		breed: 'Holland',
		petImages: [],
	},
	{
		id: 4,
		name: 'Coco',
		animal: 'cat',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		status: 'urgent',
		color: 'brown',
		description: `Meet Coco, a calm and affectionate Persian cat with a sweet personality. I'm looking for a peaceful home where I can curl up on a soft bed and purr the day away. I enjoy quiet companionship and would love to be your loyal friend.`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'puppy',
		breed: 'Persian',
		petImages: [
			{ id: 1, src: '/img/cat-2.jpg' },
			{ id: 2, src: '/img/cat-1.jpg' },
			{ id: 3, src: '/img/cat-3.jpg' },
			{ id: 4, src: '/img/cat-4.jpg' },
			{ id: 5, src: '/img/cat-5.jpg' },
		],
	},
	{
		id: 5,
		name: 'Mr. Cloud',
		animal: 'rabbit',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		color: 'white',
		description: `I’m Mr. Cloud, a fluffy white rabbit with a love for soft petting and gentle care. I would thrive in a calm environment where I can be spoiled with treats and warm cuddles. I'm as sweet as my name suggests!`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Holland',
		petImages: [
			{ id: 1, src: '/img/rabbit-2.jpg' },
			{ id: 2, src: '/img/rabbit-1.jpg' },
			{ id: 3, src: '/img/rabbit-3.jpg' },
			{ id: 4, src: '/img/rabbit-4.jpg' },
			{ id: 5, src: '/img/rabbit-5.jpg' },
		],
	},
	{
		id: 6,
		name: 'Pebbles',
		animal: 'dog',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		status: 'urgent',
		color: 'brown',
		description: `I'm Pebbles, a friendly, medium-sized Labrador with a love for outdoor activities. I’m happiest when playing fetch or going for long walks. If you're looking for a loyal friend with a calm temperament, I'm the perfect match!`,
		characteristics: ['cute', 'friendly'],
		size: 'm',
		gender: 'male',
		age: 'adult',
		breed: 'Labrador',
		petImages: [
			{ id: 1, src: '/img/dog-2.jpg' },
			{ id: 2, src: '/img/dog-1.jpg' },
			{ id: 3, src: '/img/dog-3.jpg' },
			{ id: 4, src: '/img/dog-4.jpg' },
			{ id: 5, src: '/img/dog-5.jpg' },
		],
	},
	{
		id: 7,
		name: 'Coco',
		animal: 'cat',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		color: 'brown',
		description: `Hello! I’m Coco, a Persian cat with a soft personality. I'm gentle and friendly and looking for a quiet home where I can enjoy some peace. I love warm spots, head rubs, and would love to find a forever home.`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Persian',
		petImages: [
			{ id: 1, src: '/img/cat-3.jpg' },
			{ id: 2, src: '/img/cat-2.jpg' },
			{ id: 3, src: '/img/cat-1.jpg' },
			{ id: 4, src: '/img/cat-4.jpg' },
			{ id: 5, src: '/img/cat-5.jpg' },
		],
	},
	{
		id: 8,
		name: 'Fluffy',
		animal: 'cat',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		status: 'found',
		color: 'brown',
		description: `Fluffy here! I’m a laid-back, affectionate kitty who loves being around people. My calm and friendly nature makes me an ideal companion. I'm ready to join a loving home where I can relax and be adored.`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Persian',
		petImages: [
			{ id: 1, src: '/img/cat-5.jpg' },
			{ id: 2, src: '/img/cat-2.jpg' },
			{ id: 3, src: '/img/cat-3.jpg' },
			{ id: 4, src: '/img/cat-4.jpg' },
			{ id: 5, src: '/img/cat-1.jpg' },
		],
	},
	{
		id: 9,
		name: 'Charlie',
		animal: 'rabbit',
		location: '41.300205,2.104007',
		city: 'Barcelona',
		status: 'found',
		color: 'white',
		description: `I'm Charlie, a white Holland rabbit with a gentle nature. I would love to be part of a family where I can explore, relax, and get some gentle head rubs. If you need a low-maintenance buddy, I'm the perfect fit!`,
		characteristics: ['cute', 'friendly'],
		size: 's',
		gender: 'male',
		age: 'adult',
		breed: 'Holland',
		petImages: [
			{ id: 1, src: '/img/rabbit-3.jpg' },
			{ id: 2, src: '/img/rabbit-2.jpg' },
			{ id: 3, src: '/img/rabbit-1.jpg' },
			{ id: 4, src: '/img/rabbit-4.jpg' },
			{ id: 5, src: '/img/rabbit-5.jpg' },
		],
	},
	{
		id: 10,
		name: 'Bella',
		animal: 'dog',
		location: '41.385064,2.173403',
		city: 'Barcelona',
		color: 'black',
		description: `I'm Bella, a cheerful, small-sized Terrier mix who adores people and gets along well with other pets. I’m the perfect balance of playful and calm, making me a great fit for families or individuals alike. I'm looking for a loving home where I can be a devoted companion.`,
		characteristics: ['playful', 'affectionate'],
		size: 's',
		gender: 'female',
		age: 'young',
		breed: 'Terrier mix',
		petImages: [
			{ id: 1, src: '/img/dog-3.jpg' },
			{ id: 2, src: '/img/dog-2.jpg' },
			{ id: 3, src: '/img/dog-1.jpg' },
			{ id: 4, src: '/img/dog-4.jpg' },
			{ id: 5, src: '/img/dog-5.jpg' },
		],
	},
	{
		id: 11,
		name: 'Milo',
		animal: 'cat',
		location: '41.382894,2.177432',
		city: 'Barcelona',
		status: 'urgent',
		color: 'gray',
		description: `Hello! I’m Milo, a young and curious Russian Blue with a love for exploring. I’m independent yet affectionate and enjoy spending time near my humans. I would love a quiet home where I can roam and be adored.`,
		characteristics: ['independent', 'loyal'],
		size: 'm',
		gender: 'male',
		age: 'young',
		breed: 'Russian Blue',
		petImages: [
			{ id: 1, src: '/img/cat-3.jpg' },
			{ id: 2, src: '/img/cat-2.jpg' },
			{ id: 3, src: '/img/cat-1.jpg' },
		],
	},
	{
		id: 12,
		name: 'Daisy',
		animal: 'rabbit',
		location: '41.404518,2.184814',
		city: 'Barcelona',
		status: 'found',
		color: 'brown',
		description: `I'm Daisy, a gentle rabbit with a soft brown coat and a heart of gold. I'm looking for a loving family who appreciates quiet, sweet companionship. I’m low-maintenance and would make a great addition to any home looking for a calm, adorable friend.`,
		characteristics: ['calm', 'sweet'],
		size: 's',
		gender: 'female',
		age: 'adult',
		breed: 'Mini Rex',
		petImages: [
			{ id: 1, src: '/img/rabbit-2.jpg' },
			{ id: 2, src: '/img/rabbit-1.jpg' },
		],
	},
];
